### ISSUE TITLE
Please review my edit to the Executive Summary.

### ISSUE THREAD

**Issue by alexanderbacon** [UnomahaZombieBabies/ISQA3420#19]
Formerly, the Executive Summary said: "expose the organization to attack"

Now it says: "expose the organization to litigation or attack".

Do you agree with this change?

**Comment by josephlocke1** [comment]
I would agree, litigation and attack could be two separate issues to attend to.

**Comment by so7itud3** [comment]
Question - this is due tomorrow, right? Would you guys mind if I updated exec summary and DFD right after work tomorrow (around 5:30 pm)? I am involved in preparing for a client demo tomorrow and am currently squishing small bugs in code.

**Comment by alexanderbacon** [comment]
That's correct, tomorrow night. That would be fine with me. I've been in
the same boat for the most part. Too many fires burning at once.

**Comment by so7itud3** [comment]
This looks good to me - Let's commit Alex's change.
